#Site settings
title: Rachel M Fisher
email: fisher.rachel.m@gmail.com
author: Rachel M Fisher
description:
baseurl: /
url: http://elenaltarien.github.io

# Build settings
permalink: :title/
sass:
  sass_dir: css